<a href="https://colab.research.google.com/github/karl262/ECBD-HipolitoSerranoCarlos/blob/main/Extraccion_9B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd

In [15]:
#Conjunto de datos
datos = {
    "usuario" : ["Ana", "Luis", "Martha", "Carolina", "Sofia", "Pedro", "Elena", "Diego" ],
    "edad": [22, 35, 28, 40, 19, 31, 26, 45],
    "ciudad": ["CDMX", "Monterrey", "Guadalajara", "Puebla", "Cancun", "Merida", "Tijuana", "Toluca"],
    "compras_realizadas": [5, 12, 3, 29, 1, 7, 4, 15],
    "activo" : [True, False, True, False, True, False, True, False],
    "fecha_registro" : ["2026-01-10", "2026-01-13", "2026-01-12", "2026-01-11", "2026-01-16", "2026-01-17", "2026-01-18", "2026-01-20"],
    }

In [16]:
#Convertir a DataFrame
df = pd.DataFrame(datos)

In [17]:
df

    usuario  edad       ciudad  compras_realizadas  activo fecha_registro
0       Ana    22         CDMX                   5    True     2026-01-10
1      Luis    35    Monterrey                  12   False     2026-01-13
2    Martha    28  Guadalajara                   3    True     2026-01-12
3  Carolina    40       Puebla                  29   False     2026-01-11
4     Sofia    19       Cancun                   1    True     2026-01-16
5     Pedro    31       Merida                   7   False     2026-01-17
6     Elena    26      Tijuana                   4    True     2026-01-18
7     Diego    45       Toluca                  15   False     2026-01-20

In [18]:
df.head()

    usuario  edad       ciudad  compras_realizadas  activo fecha_registro
0       Ana    22         CDMX                   5    True     2026-01-10
1      Luis    35    Monterrey                  12   False     2026-01-13
2    Martha    28  Guadalajara                   3    True     2026-01-12
3  Carolina    40       Puebla                  29   False     2026-01-11
4     Sofia    19       Cancun                   1    True     2026-01-16

In [19]:
#Crear un DataFrame  con un millon de registros
cantidad = 1000000

In [20]:
import random

In [21]:
#Datos Aleatorios
nombres = ["Ana", "Luis", "Martha", "Carolina", "Sofia", "Pedro", "Elena", "Diego"]
ciudades = ["CDMX", "Monterrey", "Guadalajara", "Puebla", "Cancun", "Merida", "Tijuana", "Toluca"]
categorias = ["Tecnologia", "Ropa", "Hogar", "Videojuegos", "Deportes", "Calzado", "Perfumeria", "Juguetes"]

In [23]:
#Creacion del DataFrame
dfMillon = pd.DataFrame ({
    "nombre" : [random.choice(nombres) for _ in range(cantidad)],
    "edad" : [random.randint(18,70) for _ in range(cantidad)],
    "salario" : [round(random.uniform(5000, 50000), 2) for _ in range(cantidad)],
    "activo" : [random.choice([True, False]) for _ in range(cantidad)],
    "categoria" : [random.choice(categorias) for _ in range(cantidad)],
    "ciudad" : [random.choice(ciudades) for _ in range(cantidad)],
    "anio_registro" : [random.randint(2010,2026) for _ in range(cantidad)]
})

In [26]:
dfMillon.shape

(1000000, 7)

In [27]:
dfMillon.dtypes

nombre            object
edad               int64
salario          float64
activo              bool
categoria         object
ciudad            object
anio_registro      int64
dtype: object

In [29]:
dfMillon.memory_usage(deep=True).sum() /1024**2

np.float64(182.990216255188)