<a href="https://colab.research.google.com/github/karl262/ECBD-HipolitoSerranoCarlos/blob/main/Lab02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd

In [15]:
data = {
      "influencer": [
         "viajero_cancun", "playa.lovers", "cancun_lifestyle",
        "turismo_mex", "sunset.cancun", "hoteluxe_cancun",
        "foodie_cancun", "adventure_cancun","familia_en_cancun",
        "eco_turismo_cancun"
    ],
    "likes": [
        54200, 12840, 8740, 19300, 7600, 22100, 4300, 15800, 3200, 4900
    ],
    "comentarios": [
        4200, 860, 540, 1200, 310, 1750, 95, 640, 78, 210
    ],
    "fecha": [
        "2026-05-05",
        "2026-05-03",
        "2026-04-29",
        "2026-04-25",
        "2026-04-20",
        "2026-04-18",
        "2026-04-12",
        "2026-04-08",
        "2026-04-04",
        "2026-04-01"
    ],
    "tipo_post": [
        "reel_turismo",
        "foto_playa",
        "carrusel_lifestyle",
        "reel_turismo",
        "foto_playa",
        "carrusel_hotel",
        "foto_gastronomia",
        "reel_aventura",
        "foto_familiar_playa",
        "reel_ecoturismo"
    ]
}

In [16]:
df = pd.DataFrame(data)

In [17]:
df

           influencer  likes  comentarios       fecha            tipo_post
0      viajero_cancun  54200         4200  2026-05-05         reel_turismo
1        playa.lovers  12840          860  2026-05-03           foto_playa
2    cancun_lifestyle   8740          540  2026-04-29   carrusel_lifestyle
3         turismo_mex  19300         1200  2026-04-25         reel_turismo
4       sunset.cancun   7600          310  2026-04-20           foto_playa
5     hoteluxe_cancun  22100         1750  2026-04-18       carrusel_hotel
6       foodie_cancun   4300           95  2026-04-12     foto_gastronomia
7    adventure_cancun  15800          640  2026-04-08        reel_aventura
8   familia_en_cancun   3200           78  2026-04-04  foto_familiar_playa
9  eco_turismo_cancun   4900          210  2026-04-01      reel_ecoturismo

In [18]:
df.head()

         influencer  likes  comentarios       fecha           tipo_post
0    viajero_cancun  54200         4200  2026-05-05        reel_turismo
1      playa.lovers  12840          860  2026-05-03          foto_playa
2  cancun_lifestyle   8740          540  2026-04-29  carrusel_lifestyle
3       turismo_mex  19300         1200  2026-04-25        reel_turismo
4     sunset.cancun   7600          310  2026-04-20          foto_playa

In [19]:
##Crear un DataFrame de un millón de registros
cantidad = 1000000

In [20]:
import random

In [21]:
#Dato Aleatorios
influencer = [
        "viajero_cancun", "playa.lovers", "cancun_lifestyle",
        "turismo_mex", "sunset.cancun", "hoteluxe_cancun",
        "foodie_cancun", "adventure_cancun","familia_en_cancun",
        "eco_turismo_cancun"
        ]
tipo_post = [
    "reel_turismo",
    "foto_playa",
    "carrusel_lifestyle",
]

In [26]:
#Creacion del DataFrame
dfMillon = pd.DataFrame ({
    "influencer" : [random.choice(influencer) for _ in range(cantidad)],
    "likes" : [random.randint(1,10000) for _ in range(cantidad)],
    "comentarios" : [random.randint(1,1000) for _ in range(cantidad)],
    "fecha" : [random.randint(2020,2026) for _ in range(cantidad)],
    "tipo_post" : [random.choice(tipo_post) for _ in range(cantidad)]
})

In [28]:
dfMillon.shape

(1000000, 5)

In [29]:
dfMillon.dtypes

influencer     object
likes           int64
comentarios     int64
fecha           int64
tipo_post      object
dtype: object

In [27]:
dfMillon.memory_usage(deep=True).sum() /1024**2

np.float64(142.89495468139648)